config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root "fragments#index"
  get "fragments/top", to: "fragments#top"
  resources :fragments, only: [:index, :new, :create, :show] do
    member do
      resources :comments, only: [:create]
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li class="error-message"><%= message %></li>
    <% end %> 
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="top-page-header">
    <div class="title">
      <%= link_to "Thinking", "/", class:"top-title" %>
    </div>
    <ul class="navi">
    <% unless user_signed_in? %>
      <li><%= link_to  "<ゲストログイン>", users_guest_sign_in_path, method: :post, class:"guest"%></li>
      <li><%= link_to "新規登録", new_user_registration_path, class:"sign-up" %></li>
      <li><%= link_to "ログイン", new_user_session_path, class:"login" %></li>
    <% else %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname" %> </li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"log-out" %>
    <% end %>
    </ul>
  </div>
</header>

app/views/shared/_header.second.html.erb
<div class="title-logo">
  <%= link_to "Thinking", "/", class:"title-logo" %>
</div>