config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root "fragments#index"
  get "fragments/top", to: "fragments#top"
  resources :fragments, only: [:index, :new, :create, :show] do
    member do
      resources :comments, only: [:create]
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/fragment.rb
class Fragment < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :genre
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :users, through: :likes

  with_options presence: true do
    validates :title
    validates :heading_a
  end
  validates :genre_id, numericality: { other_than: 1 }
end

app/controllers/fragments_controller.rb
class FragmentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @fragments = Fragment.all.order('created_at DESC')
  end

  def new
    @fragment = Fragment.new
  end

  def create
    @fragment = Fragment.new(fragment_params)
    if @fragment.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @fragment = Fragment.find(params[:id])
    @comments = @fragment.comments
    @comment = Comment.new
    @like = Like.find_by(user_id: @fragment.user_id, fragment_id: @fragment.id)
    @like_count = Like.where(fragment_id: @fragment.id, user_id: current_user.id).count
  end

  def top
  end
  

  private

  def fragment_params
    params.require(:fragment).permit(:title, :genre_id, :heading_a, :heading_b, :heading_c, :heading_a_a, :heading_a_b, :heading_b_a, :heading_b_b, :heading_c_a, :heading_c_b, :free_memo).merge(user_id: current_user.id)
  end
end

app/helpers/fragments_helper.rb
module FragmentsHelper
end

app/views/fragments/index.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="tool-bar">
    <div class="new-btn">
      <%= link_to new_fragment_path do %>
        <i class="fas fa-edit"></i> 〜新しい目標を立てよう〜
      <% end %>
    </div>
    <div class="nickname">
      <% if user_signed_in? %>
        <%= current_user.nickname %>
      <% end %>
    </div>
  </div>
  <div class="item-contents">
    <div id="item-title">投稿一覧</div>
    <ul class="think-list">
    <% @fragments.each do | fragment |%>
        <li class="list">
          <div class="list-up">
            <div class="list-a">Name:<%= fragment.user.nickname%></div>
            <div class="list-a">Category:<%= fragment.genre.name %></div>
            <div class="list-a-btn">
              <%= link_to fragment_path(fragment.id) do %>
                <i class="far fa-hand-point-right"></i> cheak!!
              <% end %>
            </div>
          </div>
          <div class="list-down">
            Title:<%= fragment.title %>
          </div>
        </li>
    <% end %>
    </ul>
  </div> 
</div>

app/views/fragments/new.html.erb
<%= render "shared/header" %>

<div class="fragment-main">
  <%= form_with model: @fragment, url: fragments_path, class: "fragment-form", local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <div class="title-name">
      <%= f.text_field :title, class:"input-fragment", id:"title", placeholder:" 目標を掲げよう！", maxlength:"40" %>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
    </div>
    <div class="fragment-box">
      <div class="fragment-item">
        <ul>
          <%= f.text_field :heading_a, class:"input-fragment", id:"heading_a", placeholder:" 中間目標: (例) 毎日筋トレ", maxlength:"40" %>
          <li class="input-memo"><%= f.text_field :heading_a_a, class:"input-fragment", id:"heading_a_a", placeholder:" 例) 腹筋20回！", maxlength:"40" %></li>
          <li class="input-memo"><%= f.text_field :heading_a_b, class:"input-fragment", id:"heading_a_b", placeholder:" 例) 腕立て20回...etc", maxlength:"40" %></li>
        </ul>
      </div>
      <div class="fragment-item">
        <ul>
          <%= f.text_field :heading_b, class:"input-fragment", id:"heading_b", placeholder:" 中間目標", maxlength:"40" %>
          <li class="input-memo"><%= f.text_field :heading_b_a, class:"input-fragment", id:"heading_b_a", placeholder:" 今からすること", maxlength:"40" %></li>
          <li class="input-memo"><%= f.text_field :heading_b_b, class:"input-fragment", id:"heading_b_b", placeholder:" 今からすること", maxlength:"40" %></li>
        </ul>
      </div>
      <div class="fragment-item">
        <ul>
          <%= f.text_field :heading_c, class:"input-fragment", id:"heading_c", placeholder:" 中間目標 ", maxlength:"40" %>
          <li class="input-memo"><%= f.text_field :heading_c_a, class:"input-fragment", id:"heading_c_a", placeholder:" hoge ", maxlength:"40" %></li>
          <li class="input-memo"><%= f.text_field :heading_c_b, class:"input-fragment", id:"heading_c_b", placeholder:" hoge ", maxlength:"40" %></li>
        </ul>
      </div>
    </div>
    <div class="free-space">
       <%= f.text_area :free_memo, class:"input-free", id:"free_memo", placeholder:" 備考欄: 例)参考Youtube URL, 決意表明etc... ", maxlength:"200" %>
    </div>
    <div class="flagment-footer">
      <%= f.submit "これで決定!!", class:"fragment-btn" %>
    </div> 
  <% end %>
</div>

app/views/fragments/show.html.erb
<%= render "shared/header" %>
<div class="fragment-main">
  <div class="fragment-show-form">
    <div class="title-name">
      <div class="show-fragment"><%= @fragment.title %></div>
        <div class="like">
          <% unless Like.find_by(user_id: current_user.id, fragment_id: @fragment.id) %>
            <%= form_with model: @like, url: likes_path(@fragment.id), id: "like-create", remote: true do |f| %>
              <%= f.button type ="submit", class: "like-btn", style: 'border-style: none;' do %>
                <div id="icon-create"><i class="far fa-grin-wink"> good!!</i></div>
              <% end %>
              <div id="like-p"><p><%= "#{@like_count}" %>人</p></div>
            <% end %>
          <% else %>
            <%= form_with model: @like, url: like_path(@fragment.id, @like.id), id: "like-destroy", method: :delete, remote: true do |f| %>
              <%= f.button type ="submit", class: "like-btn", style: 'border-style: none;' do %>
                <div id="icon-change"><i class="far fa-grin-wink" >good!!済み</i></div>
              <% end %>
              <div id="like-p"><p><%= "#{@like_count}" %>人</p></div>
            <% end %>
          <% end %>
        </div>
      </div>
    <div class="fragment-box">
      <div class="fragment-item">
        <ul>
          <div class="show-fragment"><%= @fragment.heading_a%></div>
          <li class="input-memo">
            <div class="show-fragment"><%= @fragment.heading_a_a%></div>
          </li>
          <li class="input-memo">
            <div class="show-fragment"><%= @fragment.heading_a_b%></div>
          </li>
        </ul>
      </div>
      <div class="fragment-item">
        <ul>
          <div class="show-fragment"><%= @fragment.heading_b%></div>
          <li class="input-memo">
            <div class="show-fragment"><%= @fragment.heading_b_a%></div>
          </li>
          <li class="input-memo">
            <div class="show-fragment"><%= @fragment.heading_b_b%></div>
          </li>
        </ul>
      </div>
      <div class="fragment-item">
        <ul>
          <div class="show-fragment"><%= @fragment.heading_c%></div>
          <li class="input-memo">
            <div class="show-fragment"><%= @fragment.heading_c_a%></div>
          </li>
          <li class="input-memo">
            <div class="show-fragment"><%= @fragment.heading_c_b%></div>
          </li>
        </ul>
      </div>
    </div>
    <% if @fragment.free_memo? %>
      <div class="under-space">
        <%= @fragment.free_memo %>
      </div>
    <% end %>
    <%= form_with model: @comment, url: comments_path(@fragment.id), class: "comment-form", remote: true do |f| %>
    <div class="comennt-left">
      <%= f.text_area :comment, class:"comment", id:"comment", placeholder:"コメントしよう!!", maxlength:"200" %>
    </div>
    <div class="comment-right">
      <%= f.submit "投稿", class:"comment-btn" %>
    </div>
    <% end %>
    <div id="comment-field">
    <% @comments.reverse_each do |comment| %>
      <p><%= comment.user.nickname %> : <%= comment.comment %>  <a><%= l comment.created_at %></a></p>
    <% end %>
  </div>
  </div>
</div>

app/views/fragments/top.html.erb
<%= render "shared/header" %>
<div id="top-title">自分の投稿</div>
<div id="send-index">投稿一覧</div>